import CallToAction from "@/components/home/CallToAction";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import { ThemeProvider } from "@/components/home/theme-provider";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid gap-4 items-center justify-items-center py-2 px-4 sm:px-8 sm:py-4 max-w-xl lg:max-w-4xl mx-auto relative">
            <Header />
            <main className="w-full">{children}</main>
            <CallToAction />
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
